[package]
name = "movie_maker"
version = "0.1.0"
authors = ["greg <gperlman27@gmail.com>"]

[dependencies]
web-view = "0.4.0"
glob = "0.2.11"
serde_json = "1.0.33"
serde_derive = "1.0.82"
serde = "1.0.82"
open = "1.2.2"